include:
  project: 'Duke-ARTIQ/ci-scripts'
  file: '/envs.yml'

stages:
  - test
  - deploy

.conda_env:
  image: ubuntu
  tags:
    - docker
  variables:
    CONDA_SCRIPT: "$HOME/miniconda.sh"
    CONDA_DIR: "$HOME/miniconda"
  before_script:
    # Setup Conda
    - apt-get -qq update; apt-get -qq -y install wget
    - wget -nv -O $CONDA_SCRIPT https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash $CONDA_SCRIPT -b -p $CONDA_DIR
    - source $CONDA_DIR/bin/activate
    - conda init
    - source ~/.bashrc
    # Create and activate environment
    - conda env create -n env -f $CONDA_ENV_FILE
    - conda activate env

test_nix:
  extends: .nix_env
  stage: test
  coverage: '/^TOTAL.+?(\d+\.\d+\%)$/'
  variables:
    NIX_SHELL_FILE: "test/shell.nix"
  script:
    # Run test commands
    - python3 --version
    - mypy --version; mypy
    - flake8 --version; flake8
    - coverage --version; coverage run -m pytest -v -rs
    - coverage report
    # Run build commands
    - nix-build ./default.nix --no-out-link
    - nix-shell ./shell.nix --run "python3 -c 'import dax; print(dax.__version__)'"

test_conda:
  extends: .conda_env
  stage: test
  variables:
    CONDA_ENV_FILE: "test/environment.yml"
  script:
    # Run test commands
    - python3 --version
    - mypy --version; mypy
    - flake8 --version; flake8
    - pytest -v -rs

pages:
  extends: .nix_env
  stage: deploy
  variables:
    NIX_SHELL_FILE: "doc/shell.nix"
  script:
    # Generate documentation
    - make -C doc/ html
    - mv doc/build/html/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
