include:
  project: 'Duke-ARTIQ/ci-scripts'
  file: '/envs.yml'

stages:
  - test
  - deploy

test_nix:
  extends: .nix_flake_env
  stage: test
  coverage: '/^TOTAL.+?(\d+\.\d+\%)$/'
  variables:
    NIX_DEV_ENV: "default"
    UPDATE_FLAKE: 1
  script:
    # Run test commands
    - python3 --version
    - mypy --version; mypy
    - flake8 --version; flake8
    - coverage --version; coverage run -m pytest -v -rs
    - coverage report

test_conda:
  extends: .conda_env
  stage: test
  allow_failure: false
  variables:
    CONDA_ENV_FILE: "test/environment.yml"
  script:
    # Run test commands
    - python3 --version
    - mypy --version; mypy
    - flake8 --version; flake8
    - pytest -v -rs

test_hardware:
  extends: .nix_env
  stage: test
  tags:
    - kasli
  variables:
    NIX_SHELL_FILE: "test/shell.nix"
    HW_TEST_ENABLED: "1"
  script:
    # Run test commands
    - python3 --version
    - pytest -v -rs --log-cli-level info test/hw_test/

pages:
  extends: .nix_env
  stage: deploy
  variables:
    NIX_SHELL_FILE: "doc/shell.nix"
  script:
    # Generate documentation
    - make -C doc/ html
    - mv doc/build/html/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
