stages:
  - test
  - deploy

.nix_env:
  image: nixos/nix:latest
  before_script:
    # Setup Nix channels
    - nix-channel --add https://nixbld.m-labs.hk/channel/custom/artiq/full/artiq-full
    - nix-channel --remove nixpkgs
    - nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs
    - nix-channel --update
    # Add M-Lab public key
    - mkdir -p ~/.config/nix/
    - echo "substituters = https://cache.nixos.org https://nixbld.m-labs.hk" > ~/.config/nix/nix.conf
    - echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nixbld.m-labs.hk-1:5aSRVA5b320xbNvu30tqxVPXpld73bhtOeH6uAjRyHc=" >> ~/.config/nix/nix.conf

.conda_env:
  image: ubuntu
  variables:
    CONDA_SCRIPT: "$TEMP/miniconda.sh"
    CONDA_DIR: "$HOME/miniconda"
  before_script:
    # Setup conda
    - apt-get -q update; apt-get -q -y install wget
    - wget -nv -O $CONDA_SCRIPT https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash $CONDA_SCRIPT -b -p $CONDA_DIR
    - source $CONDA_DIR/bin/activate
    - conda init
    - source ~/.bashrc
    # Install ARTIQ and activate environment
    - conda config --prepend channels https://conda.m-labs.hk/artiq
    - conda config --append channels conda-forge
    - conda create -y -n artiq artiq
    - conda activate artiq
    # Install DAX dependencies
    - conda install -y numpy scipy "pyvcd<=0.2.0" natsort pygit2 pyqt pyqtgraph matplotlib python-graphviz h5py

test_nix:
  extends: .nix_env
  stage: test
  coverage: '/^TOTAL.+?(\d+\%)$/'
  variables:
    NIX_CMD: "nix-shell test/shell.nix --run"
  script:
    # Run test commands
    - $NIX_CMD "python3 --version"
    - $NIX_CMD "coverage --version; coverage run -m unittest -v"
    - $NIX_CMD "coverage report"
    - $NIX_CMD "mypy --version; mypy"
    - $NIX_CMD "flake8 --version; flake8"

test_conda:
  extends: .conda_env
  stage: test
  script:
    # Install packages required for testing
    - conda install -y pycodestyle mypy flake8
    # Run test commands
    - python3 --version
    - python3 -m unittest -v
    - mypy --version; mypy
    - flake8 --version; flake8
  rules:
    # Rule to allow failure of conda test if variable is set
    - if: '$CONDA_ALLOW_FAILURE'
      allow_failure: true
    # Default
    - when: on_success

pages:
  extends: .nix_env
  stage: test
  variables:
    NIX_CMD: "nix-shell doc/shell.nix --run"
  script:
    # Generate documentation
    - $NIX_CMD "cd doc; make html"
    - mv doc/build/html/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
