.nix_env:
  image: nixos/nix:latest
  before_script:
    # Setup Nix channels
    - nix-channel --add https://nixbld.m-labs.hk/channel/custom/artiq/full/artiq-full
    - nix-channel --remove nixpkgs
    - nix-channel --add https://nixos.org/channels/nixos-19.09 nixpkgs
    - nix-channel --update
    # Add M-Lab public key
    - mkdir -p ~/.config/nix/
    - echo "substituters = https://cache.nixos.org https://nixbld.m-labs.hk" > ~/.config/nix/nix.conf
    - echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nixbld.m-labs.hk-1:5aSRVA5b320xbNvu30tqxVPXpld73bhtOeH6uAjRyHc=" >> ~/.config/nix/nix.conf

test_nix:
  extends: .nix_env
  script:
    # Run test commands in a Nix shell
    - nix-shell test/shell.nix --run "python --version"
    - nix-shell test/shell.nix --run "mypy --version; mypy dax/base/ dax/sim/ dax/util/"
    - nix-shell test/shell.nix --run "flake8 --version; flake8"
    - nix-shell test/shell.nix --run "coverage --version; coverage run -m unittest"
    - nix-shell test/shell.nix --run "coverage report"

test_conda:
  image: continuumio/miniconda3:latest
  before_script:
    # Install ARTIQ and activate environment
    - wget https://raw.githubusercontent.com/m-labs/artiq/release-5/install-with-conda.py
    - sed -i '/artiq-board/d' install-with-conda.py  # Remove ARTIQ board packages
    - python install-with-conda.py
    - rm install-with-conda.py
    - conda init
    - source ~/.bashrc
    - conda activate artiq
    # Install DAX dependencies
    - conda install numpy scipy pyvcd natsort GitPython
    # Install packages required for testing
    - conda install pycodestyle
  script:
    # Run test commands
    - python -m unittest

pages:
  extends: .nix_env
  script:
    # Generate documentation
    - nix-shell doc/shell.nix --run "cd doc; make html"
    - mv doc/build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
